Ask for the input matrix

In [2]:
import math
import numpy as np

In [7]:
def matrix_check_spd(matA):
  check1=np.array_equal(matA,matA.T)
  if check1:
    check2=np.all(np.linalg.eigvals(matA)>0)
    if check2:
      return True

  return False


In [3]:
def cholesky(A):
    n = len(A)
    L = [[0]*n for _ in range(n)]

    for i in range(n):
        for j in range(i+1):
            s = sum(L[i][k] * L[j][k] for k in range(j))

            if i == j:
                L[i][j] = math.sqrt(A[i][i] - s)
            else:
                L[i][j] = (A[i][j] - s) / L[j][j]

    return np.array(L)


In [4]:
size=int(input("Enter the size of the square matrix: "))
print(f"The size of the is {size} x {size}")

Enter the size of the square matrix: 4
The size of the is 4 x 4


1Entering the elements in the square matrix A

In [5]:
A=[]
for i in range(0,size):
  row=[]
  for j in range(0,size):
    x=int(input(f"Enter the element at position {i+1},{j+1}: "))
    row.append(x)
  A.append(row)

for row in A:
  print(row)

Enter the element at position 1,1: 16
Enter the element at position 1,2: 4
Enter the element at position 1,3: 4
Enter the element at position 1,4: -4
Enter the element at position 2,1: 4
Enter the element at position 2,2: 10
Enter the element at position 2,3: 4
Enter the element at position 2,4: 2
Enter the element at position 3,1: 4
Enter the element at position 3,2: 4
Enter the element at position 3,3: 6
Enter the element at position 3,4: -2
Enter the element at position 4,1: -4
Enter the element at position 4,2: 2
Enter the element at position 4,3: -2
Enter the element at position 4,4: 4
[16, 4, 4, -4]
[4, 10, 4, 2]
[4, 4, 6, -2]
[-4, 2, -2, 4]


In [6]:
matA= np.array(A)
print(matA)

[[16  4  4 -4]
 [ 4 10  4  2]
 [ 4  4  6 -2]
 [-4  2 -2  4]]


To check whether symmetric or not

In [8]:
if matrix_check_spd(matA):
  print(f"Given matrix is a symmetric and positive definite matrix")

Given matrix is a symmetric and positive definite matrix


In [11]:
print(f"The lower triangluar matrix is \n {cholesky(A)}")

The lower triangluar matrix is 
 [[ 4.  0.  0.  0.]
 [ 1.  3.  0.  0.]
 [ 1.  1.  2.  0.]
 [-1.  1. -1.  1.]]
