In [1]:
import numpy as np
import math

In [2]:
import numpy as np

def gaussian_elimination(A):
    A = np.array(A, dtype=float)   # ensure division works properly
    n = len(A)                     # number of equations (rows)

    #FORWARD ELIMINATION
    for i in range(n):
        # Step 1: Make the pivot = 1
        pivot = A[i][i]
        A[i] = A[i] / pivot

        # Make all elements below pivot = 0
        for j in range(i + 1, n):
            factor = A[j][i]
            A[j] = A[j] - factor * A[i]

    for i in range(n - 1, -1, -1):           # start from bottom row
        for j in range(i - 1, -1, -1):       # eliminate above pivots
            factor = A[j][i]
            A[j] = A[j] - factor * A[i]

    return A




In [3]:
num_equations = int(input("Enter the number of equations: "))
num_variables = int(input("Enter the number of variables: "))

# For an augmented matrix, the number of rows is the number of equations
rows = num_equations
# The number of columns is the number of variables plus one (for the constants).
cols = num_variables + 1

print(f"The augmented matrix will be {rows} x {cols}.")

Enter the number of equations: 3
Enter the number of variables: 3
The augmented matrix will be 3 x 4.


In [5]:
A=[]
print("Enter your augmented matrix A: ")
for i in range(0,rows):
  row=[]
  for j in range(0,cols):
    x=int(input(f"Enter the value of A[{i}][{j}]: "))
    row.append(x)
  A.append(row)

matA=np.array(A)
print(matA)


Enter your augmented matrix A: 
Enter the value of A[0][0]: 1
Enter the value of A[0][1]: 2
Enter the value of A[0][2]: 1
Enter the value of A[0][3]: 3
Enter the value of A[1][0]: 2
Enter the value of A[1][1]: 5
Enter the value of A[1][2]: -1
Enter the value of A[1][3]: -4
Enter the value of A[2][0]: 3
Enter the value of A[2][1]: -2
Enter the value of A[2][2]: -1
Enter the value of A[2][3]: 5
[[ 1  2  1  3]
 [ 2  5 -1 -4]
 [ 3 -2 -1  5]]


In [6]:
print(f"The final output is {gaussian_elimination(A)}")

The final output is [[ 1.  0.  0.  2.]
 [ 0.  1.  0. -1.]
 [-0. -0.  1.  3.]]
