In [1]:
import numpy as np

def gram_schmidt_orthonormal(V):
    V = np.array(V, dtype=float)
    n = len(V)
    U = []

    for i in range(n):
        u = V[i]

        # subtract projections
        for j in range(i):
            proj = (np.dot(V[i], U[j]) / np.dot(U[j], U[j])) * U[j]
            u = u - proj

        # normalize
        u = u / np.linalg.norm(u)
        U.append(u)

    return np.array(U)


In [2]:
V = [[1,1,1],
     [1,0,1],
     [0,1,1]]

Q = gram_schmidt_orthonormal(V)
print(Q)


[[ 5.77350269e-01  5.77350269e-01  5.77350269e-01]
 [ 4.08248290e-01 -8.16496581e-01  4.08248290e-01]
 [-7.07106781e-01 -3.92523115e-16  7.07106781e-01]]
